numbers = input("Introduce 10 números separado por 1 espacio\n").split()
numbers = list(map(lambda x: int(x), numbers))
print(f"Números del usuario: ", end="")
print(numbers)
suma_total = sum(numbers)
print(f"suma total: {suma_total}")
mitjana = sum(numbers)/len(numbers)
print(f"mitjana: {mitjana}")
numbers.append(suma_total)
numbers.append(mitjana)
print(numbers)
